name: Test Auth

on:
  pull_request:
    paths:
      - 'Auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd Auth && npm install && npm run test:ci
